name: "Cross Platform Build"

on:
  push:
    branches: [main]
    tags: ['*']
  workflow_dispatch: {}

concurrency:
  group: ci-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: read

env:
  GO_VERSION: 1.19

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/checkout@v3
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ env.GO_VERSION }}
        cache: true
    - name: Build
      run: make -j releases
    - name: Upload Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: splitter_v*
        draft: false
        prerelease: false
